# Generated by Django 4.2 on 2023-05-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
